version: '2'
services:
    dlaca-app:
        image: dlaca
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://dlaca-mysql:3306/dlaca?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dlaca-mysql:
        extends:
            file: mysql.yml
            service: dlaca-mysql
